# Generated by Django 3.2.8 on 2021-10-30 13:36
import json

from django.db import migrations
from pokemontcgsdk import Card, Type


def get_energy_cards(apps, schema_editor):
    CardModel = apps.get_model('deck', 'Card')

    all_energy_cards = Card.where(q=F'supertype:energy')
    energy_cards = []

    for energy_type in Type.all():
        for card in all_energy_cards:
            if F'{energy_type}' in card.name:
                energy_cards.append(card)
                break

    for card in energy_cards:
        CardModel.objects.create(
            name=card.name,
            card_id=card.id
        )


def back(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(get_energy_cards, back)
    ]
